### ISSUE TITLE
Rework Tower Build UI

### ISSUE THREAD

**Issue by naofireblade** [Milchreis/tinydefence2#13]
The current tower building ui must be reworked to overcome limitations on touch devices and to support more game features. The following points should be taken into account when planning this.
- Enable/Disable buildmode to prevent accidentally building on touch devices
- Show potential range before building ([related card](https://github.com/Milchreis/tinydefence2/projects/1#card-8258746))
- Show potential tower sprite before building/upgrading
- Choose from different towers
- Choose from different upgrade paths
- Confirm the upgrade of a tower
- Sell towers
- Confirm the sale of a tower

*These are just some ideas. Any discussion is welcome.*

**Comment by Milchreis** [comment]
IMO a smart solution could be a small and simple pop-up menu. On click on a free field the menu pops up and you could select a suitable tower. On click on a existing tower you could upgrade or sell it. The buildmode is not necessary and it works for PC and mobile. Moreover there are less permanent visible buttons on screen.

![img_20180319_130123](https://user-images.githubusercontent.com/544436/37594672-30b9c740-2b76-11e8-8e47-bdfcb643a18f.jpg)

**Comment by naofireblade** [comment]
Looks good! Some additional thoughts:
- Confirming of upgrade/build is *included* this way
- Selling might need an extra confirmation?
- Tapping on a selected field/tower should remove the build ui so that the user can build below the tower
- Holding a tower type/upgrade in the build ui should preview the sprite and range
- Releasing anywhere else then on a build ui button should abort the action

**Comment by naofireblade** [comment]
An (x) abort button should be provided to close the build ui.

**Comment by Milchreis** [comment]
Here is a concept (created in gimp) for a possible menu. It's a bit silly, because it contains build, upgrade and sell.

![concept](https://user-images.githubusercontent.com/544436/37879492-22fee8b6-307a-11e8-8cf1-2206dade2071.png)

Would do you all mean?

I think an abort-button is not necessary, because the menu could close by click outside the menu.

**Comment by naofireblade** [comment]
That looks nice. Abort is not required indeed.
- The selector should be still visibile when the buy menu is open.
- I think if we add about a maximum of 4 tower types that should fit in the menu.
- Upgrading could be an up arrow to distinguish it better from building.
- We could provide different upgrade paths (ice canon, fire canon). Then we need a fire/ice icon with a little up arrow.
- Sell and upgrade buttons should not be visible on an empty area.
- Tower build buttons should be not visible on an existing tower.
- The menu must be bigger on touch devices (detect the platfrom). But that is required for all buttons (e.g. tower range button).

**Comment by naofireblade** [comment]
Open points from pull request:

- the clicked position should be highlighted when the build ui is open so that the player can check if he builds on the correct position
- the upgrade button should be not there when the last tier is reached
- the selector should be not visible when the build ui is open or clicking on another position should open the build ui there
