### ISSUE TITLE
Level ends when all enemies currently on the map are killed without all enemies spawned

### ISSUE THREAD

**Issue by naofireblade** [Milchreis/tinydefence2#33]
When you place a good tower in front of the spawn point and the first enemy of a wave gets killed before the next enemy of the wave spawns, the level ends immediately.

**Comment by TakesTheBiscuit** [comment]
I pulled the repo and increased my money to $1500 to start, followed your bug report and could not reproduce the problem. Can you give any more info?

**Comment by Milchreis** [comment]
Hi Paul, thank you for testing out this bug. I did the same and can't reproduce it, too. I try it with other branches, but not effect. I think this bug is obsolete now. 

@naofireblade Do you remember for more?

**Comment by naofireblade** [comment]
The issue is to old for me to remember. You can close it and I will reopen an issue if I stumble across this bug again.
